CREATE TABLE USER_INFO(
	NAME VARCHAR(50),
	EMAIL VARCHAR(35),
	PASS VARCHAR(32),
	GENDER VARCHAR(7),
	BDAY DATE,
	COLLEGE_NAME VARCHAR(150),
	DEGREE_NAME VARCHAR(100),
	DEPT_NAME VARCHAR(150),
	SEMESTER VARCHAR(1),
	ROLL_NO VARCHAR(25) NOT NULL,
	REG_MONTH VARCHAR(2),
	REG_YEAR VARCHAR(4),
	CONSTRAINT PK_EMAIL PRIMARY KEY(EMAIL),
	CONSTRAINT PK_EMAIL_ROLL UNIQUE(EMAIL,ROLL_NO)
 );